"""create_fund_entity_tables

Revision ID: 3328ca9d857f
Revises: 868add1a9e21
Create Date: 2025-06-26 22:15:05.310577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3328ca9d857f'
down_revision = '868add1a9e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_pan', sa.String(length=20), nullable=False),
    sa.Column('entity_address', sa.String(), nullable=True),
    sa.Column('entity_telephone', sa.String(length=20), nullable=True),
    sa.Column('entity_email', sa.String(length=255), nullable=True),
    sa.Column('entity_poc', sa.String(length=255), nullable=True),
    sa.Column('entity_registration_number', sa.String(length=100), nullable=True),
    sa.Column('entity_tan', sa.String(length=20), nullable=True),
    sa.Column('entity_date_of_incorporation', sa.Date(), nullable=True),
    sa.Column('entity_gst_number', sa.String(length=30), nullable=True),
    sa.Column('entity_poc_din', sa.String(length=20), nullable=True),
    sa.Column('entity_poc_pan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("entity_type IN ('Manager', 'Sponsor', 'Trust', 'Custodian', 'RTA', 'Trustee', 'Auditor', 'Merchant Banker', 'Legal Advisor', 'Compliance Officer', 'Accountant', 'Tax')", name='valid_entity_type'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('fund_compliance_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('fund_details',
    sa.Column('fund_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('scheme_status', sa.String(length=40), nullable=False),
    sa.Column('aif_name', sa.String(length=255), nullable=False),
    sa.Column('aif_pan', sa.String(length=20), nullable=False),
    sa.Column('aif_registration_no', sa.String(length=50), nullable=False),
    sa.Column('legal_structure', sa.String(length=50), nullable=False),
    sa.Column('category_subcategory', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_pan', sa.String(length=20), nullable=True),
    sa.Column('entity_email', sa.String(length=255), nullable=True),
    sa.Column('entity_address', sa.Text(), nullable=True),
    sa.Column('custodian_name', sa.String(length=255), nullable=True),
    sa.Column('rta_name', sa.String(length=255), nullable=True),
    sa.Column('compliance_officer_name', sa.String(length=255), nullable=True),
    sa.Column('compliance_officer_email', sa.String(length=255), nullable=True),
    sa.Column('compliance_officer_phone', sa.String(length=20), nullable=True),
    sa.Column('investment_officer_name', sa.String(length=255), nullable=True),
    sa.Column('investment_officer_designation', sa.String(length=100), nullable=True),
    sa.Column('investment_officer_pan', sa.String(length=20), nullable=True),
    sa.Column('investment_officer_din', sa.String(length=20), nullable=True),
    sa.Column('date_of_appointment', sa.Date(), nullable=True),
    sa.Column('scheme_pan', sa.String(length=20), nullable=True),
    sa.Column('scheme_structure_type', sa.String(length=40), nullable=True),
    sa.Column('date_final_draft_ppm', sa.Date(), nullable=True),
    sa.Column('date_sebi_ppm_comm', sa.Date(), nullable=True),
    sa.Column('date_launch_of_scheme', sa.Date(), nullable=True),
    sa.Column('date_initial_close', sa.Date(), nullable=True),
    sa.Column('date_final_close', sa.Date(), nullable=True),
    sa.Column('commitment_initial_close_cr', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('terms_end_date', sa.Date(), nullable=True),
    sa.Column('extension_permitted', sa.Boolean(), nullable=True),
    sa.Column('extended_end_date', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=15), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_no', sa.String(length=50), nullable=True),
    sa.Column('bank_contact_person', sa.String(length=255), nullable=True),
    sa.Column('bank_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('nav', sa.Integer(), nullable=True),
    sa.Column('target_fund_size', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('greenshoe_option', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('fund_id'),
    sa.UniqueConstraint('aif_pan'),
    sa.UniqueConstraint('bank_account_no'),
    sa.UniqueConstraint('scheme_name')
    )
    op.create_table('lp_compliance_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('portfolio_compliance_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('fund_entities',
    sa.Column('fund_entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_role', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['fund_details.fund_id'], ),
    sa.PrimaryKeyConstraint('fund_entity_id')
    )
    op.drop_index('ix_audit_logs_activity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_compliance_records_entity_type', table_name='compliance_records')
    op.drop_index('ix_compliance_records_lp_id', table_name='compliance_records')
    op.drop_index('idx_document_category', table_name='documents')
    op.drop_index('idx_document_date_uploaded', table_name='documents')
    op.drop_index('idx_document_name', table_name='documents')
    op.drop_index('idx_document_status', table_name='documents')
    op.add_column('lp_details', sa.Column('fund_id', sa.Integer(), nullable=True))
    op.alter_column('lp_details', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Waiting For KYC'::character varying"))
    op.drop_index('ix_lp_details_email', table_name='lp_details')
    op.drop_index('ix_lp_details_pan', table_name='lp_details')
    op.create_foreign_key(None, 'lp_details', 'fund_details', ['fund_id'], ['fund_id'])
    op.add_column('lp_drawdowns', sa.Column('fund_id', sa.Integer(), nullable=True))
    op.drop_index('ix_lp_drawdowns_lp_id', table_name='lp_drawdowns')
    op.create_foreign_key(None, 'lp_drawdowns', 'fund_details', ['fund_id'], ['fund_id'])
    op.drop_constraint('uq_task_document', 'task_documents', type_='unique')
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('uq_task_document', 'task_documents', ['compliance_task_id', 'document_id'])
    op.drop_constraint(None, 'lp_drawdowns', type_='foreignkey')
    op.create_index('ix_lp_drawdowns_lp_id', 'lp_drawdowns', ['lp_id'], unique=False)
    op.drop_column('lp_drawdowns', 'fund_id')
    op.drop_constraint(None, 'lp_details', type_='foreignkey')
    op.create_index('ix_lp_details_pan', 'lp_details', ['pan'], unique=True)
    op.create_index('ix_lp_details_email', 'lp_details', ['email'], unique=True)
    op.alter_column('lp_details', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Waiting For KYC'::character varying"))
    op.drop_column('lp_details', 'fund_id')
    op.create_index('idx_document_status', 'documents', ['status'], unique=False)
    op.create_index('idx_document_name', 'documents', ['name'], unique=False)
    op.create_index('idx_document_date_uploaded', 'documents', ['date_uploaded'], unique=False)
    op.create_index('idx_document_category', 'documents', ['category'], unique=False)
    op.create_index('ix_compliance_records_lp_id', 'compliance_records', ['lp_id'], unique=False)
    op.create_index('ix_compliance_records_entity_type', 'compliance_records', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_activity', 'audit_logs', ['activity'], unique=False)
    op.drop_table('fund_entities')
    op.drop_table('portfolio_compliance_records')
    op.drop_table('lp_compliance_records')
    op.drop_table('fund_details')
    op.drop_table('fund_compliance_records')
    op.drop_table('entities')
    # ### end Alembic commands ###
