"""add_subsector_and_modify_sector_to_arrays

Revision ID: 34dc01a6362b
Revises: aa79344e58bf
Create Date: 2025-08-24 13:02:13.022637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34dc01a6362b'
down_revision = 'aa79344e58bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add subsector column as array
    op.add_column('portfolio_companies', sa.Column('subsector', sa.ARRAY(sa.String(length=100)), nullable=True))
    
    # Convert existing sector column from string to array
    # First, create a temporary column
    op.add_column('portfolio_companies', sa.Column('sector_temp', sa.ARRAY(sa.String(length=100)), nullable=True))
    
    # Copy data from sector to sector_temp as single-element arrays
    op.execute("UPDATE portfolio_companies SET sector_temp = ARRAY[sector] WHERE sector IS NOT NULL")
    
    # Drop the old sector column
    op.drop_column('portfolio_companies', 'sector')
    
    # Rename sector_temp to sector
    op.alter_column('portfolio_companies', 'sector_temp', new_column_name='sector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert sector array back to string (take first element)
    op.add_column('portfolio_companies', sa.Column('sector_temp', sa.String(length=100), nullable=True))
    
    # Copy first element of sector array to sector_temp
    op.execute("UPDATE portfolio_companies SET sector_temp = sector[1] WHERE sector IS NOT NULL AND array_length(sector, 1) > 0")
    
    # Drop the array sector column
    op.drop_column('portfolio_companies', 'sector')
    
    # Rename sector_temp to sector
    op.alter_column('portfolio_companies', 'sector_temp', new_column_name='sector')
    
    # Drop subsector column
    op.drop_column('portfolio_companies', 'subsector')
    # ### end Alembic commands ###
