"""remove_entity_role_from_fund_entities

Revision ID: b64e4dcae6fd
Revises: b1872ef84276
Create Date: 2025-06-28 13:46:53.086119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64e4dcae6fd'
down_revision = 'b1872ef84276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_entities', 'entity_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_entities', sa.Column('entity_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
