"""add_payment_reconciliation_tables

Revision ID: c3243d35eb04
Revises: 5df532b67c5f
Create Date: 2025-08-17 19:50:54.819482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3243d35eb04'
down_revision = '5df532b67c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_reconciliation',
    sa.Column('payment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_s3_link', sa.String(length=200), nullable=True),
    sa.Column('recon_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('drawdown_quarter', sa.String(length=15), nullable=False),
    sa.Column('total_expected', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_received', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('processed_payments', sa.Integer(), nullable=False),
    sa.Column('matched_payments', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund_details.fund_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('lp_payments',
    sa.Column('lp_payment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lp_id', sa.UUID(), nullable=False),
    sa.Column('drawdown_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=15), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drawdown_id'], ['lp_drawdowns.drawdown_id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['fund_details.fund_id'], ),
    sa.ForeignKeyConstraint(['lp_id'], ['lp_details.lp_id'], ),
    sa.PrimaryKeyConstraint('lp_payment_id')
    )
    op.alter_column('lp_details', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Waiting for KYC'::character varying"))
    op.drop_index('idx_lp_details_email_for_drawdowns', table_name='lp_details')
    op.drop_index('idx_lp_details_pan', table_name='lp_details')
    op.drop_index('idx_lp_documents_document_type', table_name='lp_documents')
    op.drop_index('idx_lp_documents_lp_id', table_name='lp_documents')
    op.alter_column('lp_drawdowns', 'notice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('lp_drawdowns', 'drawdown_due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('lp_drawdowns', 'drawdown_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('lp_drawdowns', 'committed_amt',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('lp_drawdowns', 'drawdown_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('lp_drawdowns', 'amount_called_up',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('lp_drawdowns', 'remaining_commitment',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.drop_index('idx_portfolio_documents_company_id', table_name='portfolio_documents')
    op.drop_index('idx_portfolio_founders_company_id', table_name='portfolio_founders')
    op.drop_index('idx_portfolio_investments_company_id', table_name='portfolio_investments')
    op.drop_index('idx_portfolio_investments_fund_id', table_name='portfolio_investments')
    op.drop_index('idx_portfolio_investments_funding_date', table_name='portfolio_investments')
    op.alter_column('unit_allotments', 'nav_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('idx_unit_allotments_created_at', table_name='unit_allotments')
    op.drop_index('idx_unit_allotments_drawdown_quarter', table_name='unit_allotments')
    op.drop_index('idx_unit_allotments_fund_id', table_name='unit_allotments')
    op.drop_index('idx_unit_allotments_lp_id', table_name='unit_allotments')
    op.drop_index('idx_unit_allotments_status', table_name='unit_allotments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unit_allotments_status', 'unit_allotments', ['status'], unique=False)
    op.create_index('idx_unit_allotments_lp_id', 'unit_allotments', ['lp_id'], unique=False)
    op.create_index('idx_unit_allotments_fund_id', 'unit_allotments', ['fund_id'], unique=False)
    op.create_index('idx_unit_allotments_drawdown_quarter', 'unit_allotments', ['drawdown_quarter'], unique=False)
    op.create_index('idx_unit_allotments_created_at', 'unit_allotments', ['created_at'], unique=False)
    op.alter_column('unit_allotments', 'nav_value',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_index('idx_portfolio_investments_funding_date', 'portfolio_investments', ['funding_date'], unique=False)
    op.create_index('idx_portfolio_investments_fund_id', 'portfolio_investments', ['fund_id'], unique=False)
    op.create_index('idx_portfolio_investments_company_id', 'portfolio_investments', ['company_id'], unique=False)
    op.create_index('idx_portfolio_founders_company_id', 'portfolio_founders', ['company_id'], unique=False)
    op.create_index('idx_portfolio_documents_company_id', 'portfolio_documents', ['company_id'], unique=False)
    op.alter_column('lp_drawdowns', 'remaining_commitment',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('lp_drawdowns', 'amount_called_up',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('lp_drawdowns', 'drawdown_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('lp_drawdowns', 'committed_amt',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('lp_drawdowns', 'drawdown_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('lp_drawdowns', 'drawdown_due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('lp_drawdowns', 'notice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index('idx_lp_documents_lp_id', 'lp_documents', ['lp_id'], unique=False)
    op.create_index('idx_lp_documents_document_type', 'lp_documents', ['document_type'], unique=False)
    op.create_index('idx_lp_details_pan', 'lp_details', ['pan'], unique=False)
    op.create_index('idx_lp_details_email_for_drawdowns', 'lp_details', ['email_for_drawdowns'], unique=False)
    op.alter_column('lp_details', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Waiting for KYC'::character varying"))
    op.drop_table('lp_payments')
    op.drop_table('payment_reconciliation')
    # ### end Alembic commands ###
